# Explicitly set this half as a split peripheral node
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Ensure Bluetooth is enabled to handshake with the Left side
CONFIG_ZMK_BLE=y

# Match the increased radio transmission power of the left side
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
