# Force this side to act as the primary USB central hub
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Force-enable the USB HID engine
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
# CONFIG_USB_HID_DEVICE_COUNT=1
# CONFIG_USB_HID_BOOT_PROTOCOL=y

# Prioritize USB over Bluetooth when a wire is attached
# CONFIG_ZMK_USB_BOOT=y

# Enable Bluetooth support
CONFIG_ZMK_BLE=y

# Increase radio transmission power for a stable handshake
# CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Force standard BLE speed (Intel cards on Linux choke on 2Mbps)
CONFIG_BT_CTLR_PHY_2M=n

# Adjust connection intervals to prevent Linux kernel handshaking drops
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
